# Generated by Django 4.2.4 on 2023-09-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioLab_app', '0002_institution_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.IntegerField(choices=[(1, 'fundacja'), (2, 'organizacja pozarządowa'), (3, 'zbiórka lokalna')], default=1),
        ),
    ]
